### ISSUE TITLE
When successfully processed the document should be deleted from storage

### ISSUE THREAD

**Issue by alexjoybc** [bcgov/jrcc-document-access-libs#122]
https://github.com/bcgov/jrcc-document-access-libs/blob/a3e576dec208edacfb87f81944dbd25f6e3c9abc/jrcc-access-spring-boot-autoconfigure/src/main/java/ca/bc/gov/open/jrccaccess/autoconfigure/plugins/rabbitmq/RabbitMqDocumentInput.java#L63

When successfully processed the document should be deleted from redis storage.

**Comment by sdevalapurkar** [comment]
I believe this can be closed now as it has been addressed @alexjoybc 👍
