### ISSUE TITLE
Sender Configuration

### ISSUE THREAD

**Issue by alexjoybc** [bcgov/jrcc-document-access-libs#133]
https://github.com/bcgov/jrcc-document-access-libs/blob/04cb3beb5f4199e618a92d63d0e6c809fbb392cb/jrcc-access-spring-boot-autoconfigure/src/main/java/ca/bc/gov/open/jrccaccess/autoconfigure/AccessProperties.java#L27

Global properties should support a `sender` property. This property must be attach to the `transactionInfo`. The sender must be removed from http plugin api query string. 

This will allow to configure the sender per service basis.

**Comment by sdevalapurkar** [comment]
I will look into this :)

**Comment by sdevalapurkar** [comment]
As per discussion with @alexjoybc, we are still going to provide the option to pass in a query param (for http) to manually specify a sender if need be. Otherwise the option specified in the properties file will be used
