### ISSUE TITLE
Should display entire config in debug mode except pwd

### ISSUE THREAD

**Issue by alexjoybc** [bcgov/jrcc-document-access-libs#134]
https://github.com/bcgov/jrcc-document-access-libs/blob/04cb3beb5f4199e618a92d63d0e6c809fbb392cb/jrcc-access-spring-boot-autoconfigure/src/main/java/ca/bc/gov/open/jrccaccess/autoconfigure/plugins/sftp/AutoConfiguration.java#L45

When logger set to debug, it should print the entire config

**Comment by sdevalapurkar** [comment]
Going to look into this now 😃
