### ISSUE TITLE
Transaction must have a unique identifier

### ISSUE THREAD

**Issue by alexjoybc** [bcgov/jrcc-document-access-libs#135]
https://github.com/bcgov/jrcc-document-access-libs/blob/04cb3beb5f4199e618a92d63d0e6c809fbb392cb/jrcc-document-access-libs/src/main/java/ca/bc/gov/open/jrccaccess/libs/TransactionInfo.java#L33-L46

When creating a new `transactionInfo`, a new unique identifier must be set (UUID)

**Comment by peggy-ntt** [comment]
done with pull request #137
