### ISSUE TITLE
Document-type is prone to collision

### ISSUE THREAD

**Issue by alexjoybc** [bcgov/jrcc-document-access-libs#24]
https://github.com/bcgov/jrcc-document-access-libs/blob/8560624bc488c63679ee1c7cd90d0041ffaddba0/jrcc-access-spring-boot-autoconfigure/src/main/java/ca/gov/bc/open/jrccaccess/autoconfigure/AccessProperties.java#L26

**Comment by ChrisHoban** [comment]
Should we change the property name? Good call out
